name: Lint Code

on:
  pull_request:
    branches:
      - '*' # All branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run HTMLHint
        run: npx htmlhint 'src/**/*.html'

      - name: Run Stylelint
        run: npx stylelint 'src/css/**/*.css'
